### ISSUE TITLE
Error: Column start (16) greater than line length (9)

### ISSUE THREAD

**Issue by FlorianWendelborn** [AtomLinter/linter-gjslint#42]
I get the following error on atom 1.5.0-beta3, Kubuntu 15.10:

```
Error: Column start (16) greater than line length (9)
    at Object.rangeFromLineNumber (/home/dodekeract/.atom/packages/linter-gjslint/node_modules/atom-linter/lib/helpers.js:191:11)
    at /home/dodekeract/.atom/packages/linter-tidy/lib/main.coffee:41:29
    at process._tickCallback (node.js:368:9)
```

This seems to be related to AtomLinter/linter-tidy/issues/24 though, so I'm not sure, which package is "broken".

**Comment by Arcanemagus** [comment]
That is just bizarre, this should have been reported as coming from `linter-tidy` as that is the package responsible in this case (this package just happened to be where Atom loaded the `atom-linter` helper library from).

I haven't had time to trace down what is going on in that issue yet, I'll see if I can spare some time tomorrow...

Marking this as closed since this isn't an issue with this package.
